<?php

/**
 * @file hosting_certificate.module
 * Contains hooks for the certificate module.
 */

/**
 * Implements hook_hosting_service_type().
 */
function hosting_certificate_hosting_service_type() {
  return array(
    'Certificate' => array(
      'title' => t('Certificate'),
    ),
  );
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_certificate_hosting_feature().
 */
function hosting_certificate_feature_enable_callback() {
  drupal_set_message(t("The 'certificate' feature's <strong>enable</strong> callback was just called."));
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_certificate_hosting_feature().
 */
function hosting_certificate_feature_disable_callback() {
  drupal_set_message(t("The 'certificate' feature's <strong>disable</strong> callback was just called."));
}

