<?php
/**
 * @file
 * Hook implementations for the Hosting SSL module.
 */

/**
 * SSL is disabled for this site.
 */
define('HOSTING_HTTPS_DISABLED', 0);

/**
 * SSL is enabled for this site.
 */
define('HOSTING_HTTPS_ENABLED', 1);

/**
 * SSL is required for this site.
 */
define('HOSTING_HTTPS_REQUIRED', 2);

include_once 'hosting_https.nodeapi.inc';

/**
 * Implements hook_permission().
 */
function hosting_https_permission() {
  return array(
    'create ssl certificate' => array(
      'title' => t('create ssl certificate'),
    ),
  );
}

/**
 * Return a list of servers which have SSL enabled web services.
 */
function hosting_https_get_servers() {
  $servers = hosting_get_servers('http');
  $ssl_servers = array();
  foreach ($servers as $nid => $title) {
    $node = node_load($nid);
    if ($node->services['http']->ssl_enabled) {
      $ssl_servers[] = $nid;
    }
  }
  return $ssl_servers;
}

/**
 * Return a list of platforms on SSL enabled servers.
 */
function hosting_https_get_platforms() {
  $servers = hosting_https_get_servers();
  $ssl_platforms = array();

  $platforms = _hosting_get_platforms();
  foreach ($platforms as $nid => $title) {
    $platform = node_load($nid);
    if (in_array($platform->web_server, $servers)) {
      $ssl_platforms[] = $nid;
    }
  }

  return $ssl_platforms;
}

/**
 * Return a list of profiles with SSL enabled platforms.
 */
function hosting_https_get_profiles() {
  $platforms = hosting_https_get_platforms();

  $ssl_profiles = array();
  foreach ($platforms as $nid) {
    $platform = node_load($nid);
    $ssl_profiles = array_merge($ssl_profiles, array_keys($platform->profiles));
  }

  return array_unique($ssl_profiles);
}

/**
 * Implements hook_form_alter().
 */
function hosting_https_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    hosting_https_site_form($form, $form_state, $form_id);
  }
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_example_hosting_feature().
 */
function hosting_https_feature_enable_callback() {
  drupal_set_message(t("Please make sure you have enabled SSL support in your webserver, e.g. by enabling mod_ssl in Apache."));
  drupal_set_message(t("To start using SSL please edit the desired server node within Aegir to set in from e.g. 'apache' to 'apache_https'."));
}
