<?php
/**
 * @file
 * Hook implementations for the Hosting HTTPS module.
 */

/**
 * HTTPS is disabled for this site.
 */
define('HOSTING_HTTPS_DISABLED', 0);

/**
 * HTTPS is enabled for this site.
 */
define('HOSTING_HTTPS_ENABLED', 1);

/**
 * HTTPS is required for this site.
 */
define('HOSTING_HTTPS_REQUIRED', 2);

include_once 'hosting_https.nodeapi.inc';

/**
 * Implements hook_permission().
 * TODO: move this to the 'manual' certificate service implementation.
 */
function hosting_https_permission() {
  return array(
    'manage site HTTPS settings' => array(
      'title' => t('Manage site HTTPS settings.'),
    ),
  );
}

/**
 * Return a list of servers which have HTTPS enabled web services.
 */
function hosting_https_get_servers() {
  $servers = hosting_get_servers('http');
  $https_servers = array();
  foreach ($servers as $nid => $title) {
    $node = node_load($nid);
    if ($node->services['http']->https_enabled) {
      $https_servers[] = $nid;
    }
  }
  return $https_servers;
}

/**
 * Return a list of platforms on HTTPS enabled servers.
 */
function hosting_https_get_platforms() {
  $https_servers = hosting_https_get_servers();
  $https_platforms = array();

  $platforms = _hosting_get_platforms();
  foreach ($platforms as $nid => $title) {
    $platform = node_load($nid);
    if (in_array($platform->web_server, $https_servers)) {
      $https_platforms[] = $nid;
    }
  }

  return $https_platforms;
}

/**
 * Return a list of profiles with HTTPS enabled platforms.
 */
function hosting_https_get_profiles() {
  $https_platforms = hosting_https_get_platforms();

  $https_profiles = array();
  foreach ($https_platforms as $nid) {
    $platform = node_load($nid);
    $https_profiles = array_merge($https_profiles, array_keys($platform->profiles));
  }

  return array_unique($https_profiles);
}

/**
 * Implements hook_form_alter().
 */
function hosting_https_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    hosting_https_site_form($form, $form_state, $form_id);
  }
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_example_hosting_feature().
 */
function hosting_https_feature_enable_callback() {
  drupal_set_message(t("Please make sure you have enabled HTTPS support in your webserver, e.g. by enabling mod_ssl in Apache."));
  drupal_set_message(t("To start using HTTPS please edit the desired server node within Aegir to set it from e.g. 'apache' to 'apache_https'."));
}
