<?php
/**
 * @file Register a Hosting service for Apache w/ HTTPS
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_apache_https_hosting_service() {
  return array(
    'https_apache' => 'http',
  );
}

/**
 * Implements hook_system_info_alter().
 */
function hosting_apache_https_system_info_alter(&$info, $file, $type) {
  if ($type == 'module' && $file->name == 'hosting_https_apache') {
    hosting_certificate_prevent_orphaned_services($info, 'http', 'apache_https');
  }
}

