<?php

/**
 * @file
 * SelfSigned certificate generation service.
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_self_signed_hosting_service() {
  return array('SelfSigned' => 'Certificate');
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_self_signed_hosting_feature().
 */
function hosting_self_signed_feature_enable_callback() {
  drupal_set_message(t("The 'SelfSigned' feature's <strong>enable</strong> callback was just called."));
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_self_signed_hosting_feature().
 */
function hosting_self_signed_feature_disable_callback() {
  drupal_set_message(t("The 'SelfSigned' feature's <strong>disable</strong> callback was just called."));
}

/**
 * Implements hook_system_info_alter().
 */
function hosting_self_signed_system_info_alter(&$info, $file, $type) {
  if ($type == 'module' && $file->name == 'hosting_self_signed') {
    hosting_certificate_prevent_orphaned_services($info, 'Certificate', 'SelfSigned');
  }
}

