<?php

/**
 * @file
 * LetsEncrypt certificate generation service.
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_letsencrypt_hosting_service() {
  return array('LetsEncrypt' => 'Certificate');
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_letsencrypt_hosting_feature().
 */
function hosting_letsencrypt_feature_enable_callback() {
  drupal_set_message(t("The 'LetsEncrypt' feature's <strong>enable</strong> callback was just called."));
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_letsencrypt_hosting_feature().
 */
function hosting_letsencrypt_feature_disable_callback() {
  drupal_set_message(t("The 'LetsEncrypt' feature's <strong>disable</strong> callback was just called."));
}

/**
 * Implements hook_system_info_alter().
 */
function hosting_letsencrypt_system_info_alter(&$info, $file, $type) {
  if ($type == 'module' && $file->name == 'hosting_letsencrypt') {
    hosting_certificate_prevent_orphaned_services($info, 'Certificate', 'LetsEncrypt');
  }
}

