<?php

/**
 * @file
 * Letsencrypt SSL certificate generation service.
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_letsencrypt_hosting_service() {
  return array('Letsencrypt' => 'Certificate');
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_letsencrypt_hosting_feature().
 */
function hosting_letsencrypt_feature_enable_callback() {
  drupal_set_message(t("The 'Letsencrypt' feature's <strong>enable</strong> callback was just called."));
}

/**
 * Callback function to execute on enabling this module's feature.
 *
 * @see: hosting_letsencrypt_hosting_feature().
 */
function hosting_letsencrypt_feature_disable_callback() {
  drupal_set_message(t("The 'Letsencrypt' feature's <strong>disable</strong> callback was just called."));
}

