<?php
/**
 * @file Register a Hosting service for NGINX w/ HTTPS
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_nginx_https_hosting_service() {
  return array(
    'https_nginx' => 'http',
  );
}

/**
 * Implements hook_system_info_alter().
 */
function hosting_nginx_https_system_info_alter(&$info, $file, $type) {
  if ($type == 'module' && $file->name == 'hosting_nginx_https') {
    hosting_certificate_prevent_orphaned_services($info, 'http', 'https_nginx');
  }
}

